- name: Start Oracle VM1
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to turn on VM-1 on remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-1/start-vm1.ps1 
        dest: "C:\\Users\\DELL\\workspace\\vm1\\"

    - name: Start VM-1 using Powershell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm1\start-vm1.ps1"

- name: Start mysql service and run sql files
  hosts: vm-1
  gather_facts: no
  become: yes
  tasks:
    - name: Check if mysql files exist on VM-1
      stat:
        path: "~/bachelor/ansible-db/vm-1/mysql-sakila-db/"
      register: mysql_files_exist

    - name: Delete mysql files to pull the newest changes
      file:
        path: "~/bachelor/ansible-db/vm-1/mysql-sakila-db/"
        state: absent
      when: mysql_files_exist.stat.exists

    - name: Download mysql files
      copy:
        src: ~/bachelor/ansible-db/vm-1/mysql-sakila-db/
        dest: /home/amelia_user/mysql-sakila-db
        owner: root
        group: root        
        mode: 0777

    - name: Installing mysql and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes
      
    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create mysql user if amelia_user doesn't exist
      mysql_user:
        name: amelia_user
        password: amelia_user
        priv: '*.*:ALL'
        host: '%'
        state: present
    
    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
    
    - name: Restart mysql service
      service:
        name: mysql
        state: restarted
    
    - name: Create sakila db to exectue sql files correctly
      mysql_db:
        name: sakila
        state: present
        login_host: localhost
        login_user: amelia_user
        login_password: amelia_user

    - name: Run Insert schema script
      shell: mysql -u amelia_user -pamelia_user -h localhost sakila -e 'source /home/amelia_user/mysql-sakila-db/mysql-sakila-schema.sql'

    - name: Run Insert data script
      shell: mysql -u amelia_user -pamelia_user -h localhost sakila -e 'source /home/amelia_user/mysql-sakila-db/mysql-sakila-insert-data.sql'

    - name: Run Delete data script
      shell: mysql -u amelia_user -pamelia_user -h localhost sakila -e 'source /home/amelia_user/mysql-sakila-db/mysql-sakila-delete-data.sql'
      ignore_errors: yes
    
    - name: Run Drop schema script
      shell: mysql -u amelia_user -pamelia_user -h localhost sakila -e 'source /home/amelia_user/mysql-sakila-db/mysql-sakila-drop-objects.sql'

    - name: Drop database command
      shell: mysql -u amelia_user -pamelia_user -h localhost sakila -e 'drop database sakila;'