- name: Start Oracle VM1
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check if powershell script exists
      win_stat:
        path: "C:\\Users\\DELL\\workspace\\vm1\\start-vm1.ps1"
      register: script_file_stat

    - name: Delete PowerShell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm1\\start-vm1.ps1"
        state: absent
      when: script_file_stat.stat.exists

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-1/start-vm1.ps1
        dest: C:\Users\DELL\workspace\vm1\
      register: copy_result

    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm1\start-vm1.ps1"

- name: Start mysql service
  hosts: vm-1
  gather_facts: no
  become: yes
  tasks:
    - name: Check if MySQL files exist
      stat:
        path: "~/bachelor/ansible-db/vm-1/mysql-sakila-db/"
      register: mysql_files_exist

    - name: Delete MYSQL files to pull the newest changes
      file:
        path: "~/bachelor/ansible-db/vm-1/mysql-sakila-db/"
        state: absent
      when: mysql_files_exist.stat.exists

    - name: Download mysql files
      copy:
        src: ~/bachelor/ansible-db/vm-1/mysql-sakila-db/
        dest: /root/ansible-db/mysql-sakila-db
        owner: root
        group: root        
        mode: 0777

    - name: Installing Mysql and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev
      become: yes
      
    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: creating mysql user (medium_post)
      mysql_user:
        name: amelia_user
        password: amelia_user
        priv: '*.*:ALL'
        host: '%'
        state: present
    
    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
    
    - name: Restart MySQL service
      service:
        name: mysql
        state: restarted