- name: Start Oracle VM1
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check if powershell script exists
      win_stat:
        path: "C:\\Users\\DELL\\workspace\\vm-1\\start-vm1.ps1"
      register: script_file_stat

    - name: Delete PowerShell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm-1\\start-vm1.ps1"
        state: absent
      when: script_file_stat.stat.exists

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-1/start-vm1.ps1
        dest: C:\Users\DELL\workspace\vm-1\
      register: copy_result
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm-1\start-vm1.ps1"

- name: Start mysql service
  hosts: vm-1
  gather_facts: no
  become: yes
  tasks:
    - name: Download mysql files
      copy:
        src: ~/bachelor/ansible-db/vm-1/mysql-sakila-db/
        dest: /root/ansible-db/mysql-sakila-db
        owner: root
        group: root        
        mode: 0777
