- name: Start MSSQL VM4
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: C:\Users\DELL\workspace\vm4\start_vm4.ps1
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-4/start_vm4.ps1  # Update the path to your PowerShell script
        dest: C:\Users\DELL\workspace\vm4\  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Record the start time
      command: date +%s.%N
      register: start_time_vm
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm4\start_vm4.ps1"

    - name: Record the end time
      command: date +%s.%N
      register: end_time_vm
    
    - name: Calculate the time difference
      set_fact:
        execution_time: "{{ (end_time_vm.stdout | float - start_time_vm.stdout | float) | round(3, 'floor') }}"

    - name: Display the execution time
      debug:
        msg: "Time taken to start VM with mysql installed: {{ execution_time }} seconds"

- name: Install Microsoft SQL Server
  hosts: vm-4
  become: yes
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: "admin123"
    mssql_edition: Evaluation
    mssql_enable_sql_agent: true
    mssql_install_fts: true
    mssql_install_powershell: true
    mssql_tune_for_fua_storage: true
  roles:
    - microsoft.sql.server
