- name: Start MSSQL VM4
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm4\\start-vm4.ps1"
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-4/start-vm4.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm4\\"  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm4\start-vm4.ps1"

- name: Start mssql service
  hosts: vm-4
  gather_facts: no
  become: yes
  tasks:
    - name: Check if mssql files exist
      stat:
        path: "~/bachelor/ansible-db/vm-4/sql-server-sakila-db/"
      register: mssql_files_exist

    - name: Delete MYSQL files to pull the newest changes
      file:
        path: "~/bachelor/ansible-db/vm-4/sql-server-sakila-db/"
        state: absent
      when: mssql_files_exist.stat.exists

    - name: Download mysql files
      copy:
        src: ~/bachelor/ansible-db/vm-4/sql-server-sakila-db/
        dest: /root/ansible-db/sql-server-sakila-db
        owner: root
        group: root        
        mode: 0777