- name: Start MSSQL VM4
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-4/start-vm4.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm4\\"  # Update the destination directory as per your workspace
      register: copy_result

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-4/stop-vm4.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm4\\"  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm4\start-vm4.ps1"

- name: Start mssql service
  hosts: vm-4
  gather_facts: no
  tasks:
    - name: Download mysql files
      copy:
        src: ~/bachelor/ansible-db/vm-4/sql-server-sakila-db/
        dest: /home/amelia_user/sql-server-sakila-db/
        owner: amelia_user
        group: amelia_user        
        mode: 0777

    - name: Run Insert schema script
      become_user: amelia_user
      command: /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P Admin123! -C -i '/home/amelia_user/sql-server-sakila-db/sql-server-sakila-schema.sql'
    
    - name: Run Insert data script
      become_user: amelia_user
      command: sqlcmd -S 127.0.0.1 -U sa -P Admin123! -C -i '/home/amelia_user/sql-server-sakila-db/sql-server-sakila-insert-data.sql'

    - name: Run Delete data script
      become_user: amelia_user
      command: sqlcmd -S 127.0.0.1 -U sa -P Admin123! -C -i '/home/amelia_user/sql-server-sakila-db/sql-server-sakila-delete-data.sql'

    - name: Run Drop schema script
      become_user: amelia_user
      command: sqlcmd -S 127.0.0.1 -U sa -P Admin123! -C -i '/home/amelia_user/sql-server-sakila-db/sql-server-sakila-drop-objects.sql'