- name: Start Oracle VMS
  hosts: windows
  gather_facts: no
  tasks:
    - name: Start VirtualBox VM
      win_shell: |
        "C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" startvm "db-machine-1" --type headless
      args:
        executable: powershell.exe
