- name: Start Oracle VMS
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/start_vm.ps1  # Update the path to your PowerShell script
        dest: C:\Users\ansible\workspace\  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\ansible\workspace\start_vm.ps1"
      when: copy_result.changed
