---
- name: Start Oracle VMS
  hosts: windows
  become: false
  gather_facts: false
  tasks:
    - name: Start VM1
      ansible.windows.win_shell: VBoxManage startVM db-machine-1 --type headless
    
    - name: Start VM2
      ansible.windows.win_command: VBoxManage startVM db-machine-2 --type headless
    
    - name: Start VM3
      ansible.windows.win_command: VBoxManage startVM db-machine-3 --type headless
    
    - name: Start VM4
      ansible.windows.win_command: VBoxManage startVM db-machine-4 --type headless  

- name: Run echo command on VM
  hosts: dbserver
  become: true
  become_method: sudo
  tasks:
    - name: Execute echo command
      command: echo 'Hello, world'