- name: Start POSTGRESSQL container
  hosts: windows
  gather_facts: no
  tasks:

    - name: Pull postgres image
      win_shell: |
        docker pull postgres:latest

    - name: Attach volume and files to postgres Container
      win_shell: |
        docker run -d --name postgres-container-test -e POSTGRES_USER=sakila -e POSTGRES_PASSWORD=admin123 -e POSTGRES_DB=sakila -v C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-2\postgres-sakila-db:/tmp/postgres-sakila-db postgres:latest