- name: Start Oracle VMS
  hosts: windows
  gather_facts: no
  tasks:    
    - name: Run PowerShell script
      win_shell: |
        docker pull mysql:latest
    
    - name: Start MySQL Container
      win_shell: |
        docker run -d --name mysql_container -e MYSQL_ROOT_PASSWORD=admin123 mysql:latest

    - name: Copy Files to MySQL Container
      win_copy:
        src: "/path/to/your/files"
        dest: "C:/path/in/container"
      delegate_to: localhost

    - name: Wait for MySQL Service to Start
      wait_for:
        host: localhost
        port: 3306
        delay: 10
        timeout: 60
    
    - name: Create Database in MySQL Container
      win_shell: |
        docker exec mysql_container mysql -uroot -pyour_root_password -e "CREATE DATABASE your_database_name;"
      delegate_to: localhost

    - name: Run SQL Files in MySQL Container
      win_shell: |
        docker exec mysql_container mysql -uroot -padmin123 < /path/in/container/your_sql_file.sql
      delegate_to: localhost

