- name: Start MYSQL CONTAINER
  hosts: windows
  gather_facts: no
  tasks:

    - name: Pull mysql image
      win_shell: |
        docker pull mysql:latest

    - name: Build image
      win_shell: |
        docker build -t mysql-container:test .
      args:
        chdir: C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1

    - name: Attach volume and files to MySQL Container
      win_shell: |
        docker run -d --name mysql-container-test -e MYSQL_ROOT_PASSWORD=admin123 -v C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1\mysql-sakila-db:/tmp/mysql-sakila-db mysql-container:test

    - name: Create database
      win_shell: |
        docker exec mysql-container-test sh -c "mysql -u root -padmin123 -h 127.0.0.1 -e 'create database sakila;'"
    
    - name: Drop database
      docker_container:
        name: mysql-container-test
        command: "mysql -u root -padmin123r -e 'drop database sakila;'"