- name: Start Oracle VMS
  hosts: windows
  gather_facts: no
  tasks:

    - name: Pull mysql image
      win_shell: |
        docker pull mysql:latest

    - name: Build image
      win_shell: |
        docker build -t mysql-container:test .
      args:
        chdir: C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1
    
    # # - name: Start MySQL Container
    # #   win_shell: |
    # #     docker run -d --name mysql_container -e MYSQL_ROOT_PASSWORD=admin123 mysql:latest

    - name: Attach volume and files to MySQL Container
      win_shell: |
        docker run -d --name mysql-container-test -e MYSQL_ROOT_PASSWORD=admin123 -v C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1\mysql-sakila-db:/tmp/mysql-sakila-db mysql-container:test

    # - name: Enable remote login to MySQL
    #   win_shell: |
    #     docker exec mysql-container sh -c "echo 'bind-address = 0.0.0.0' >> /etc/mysql/my.cnf"

    # - name: Restart MySQL service
    #   win_shell: |
    #     docker exec mysql-container service mysql restart


    # - name: Wait for MySQL Service to Start
    #   wait_for:
    #     host: localhost
    #     port: 3306
    #     delay: 10
    #     timeout: 60

    # - name: Get ip
    #   win_shell: |
    #     docker inspect --format='{''{ .NetworkSettings.IPAddress }''}' mysql-container-test
    #   register: host_ip 
    
    # - name: Create Database in MySQL Container
    #   win_shell: |
    #     docker exec mysql-container-test sh -c "mysql -u root -padmin123 -e 'CREATE DATABASE sakila;'"
  
    # - name: Run sql schema
    #   win_shell: |
    #     docker exec mysql-container-test sh -c "mysql -u root -padmin123 -h 172.17.0.2 sakila < /tmp/mysq-sakila-db/mysql-sakila-schema.sql"

    # - name: Run insert data
    #   win_shell: |
    #     docker exec mysql-container-test sh -c "mysql -u root -padmin123 -h 172.17.0.2 sakila < /tmp/mysq-sakila-db/mysql-insert-data.sql"

    # - name: Run delete data
    #   win_shell: |
    #     docker exec mysql-container-test sh -c "mysql -u root -padmin123 -h 172.17.0.2 sakila < /tmp/mysq-sakila-db/mysql-delete-data.sql"

    # - name: Run delete schema
    #   win_shell: |
    #     docker exec mysql-container-test sh -c "mysql -u root -padmin123 -h 172.17.0.2 sakila < /tmp/mysq-sakila-db/mysql-drop-objects.sql"
