- name: Start MYSQL CONTAINER
  hosts: windows
  gather_facts: no
  tasks:

    - name: Pull mysql image
      win_shell: |
        docker pull mysql:latest

    - name: Build image
      win_shell: |
        docker build -t mysql-container:test .
      args:
        chdir: C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1

    - name: Attach volume and files to MySQL Container
      win_shell: |
        docker run -d --name mysql-container-test -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin123 -v C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1\mysql-sakila-db:/tmp/mysql-sakila-db mysql-container:test

    - name: Introduce a delay using Start-Sleep in win_shell
      win_shell: Start-Sleep -Seconds 20

    - name:
      win_shell: |
        C:\Users\DELL\Desktop\licencjat\bachelor\docker-db\docker-1\mysql-script.sh