- name: Start Oracle VM3
  hosts: windows
  gather_facts: no
  tasks:
    # - name: Delete powershell script to pull the newest changes
    #   win_file:
    #     path: "C:\\Users\\DELL\\workspace\\vm3\\"
    #     state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/start-vm3.ps1
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"  
      register: copy_result

    - name: Copy db scripts to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/sql-scripts/
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"

    - name: Start vm-3 using powershell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm3\start-vm3.ps1"

    # - name: Run Insert schema script
    #   win_shell: |
    #     "bash /c/Users/DELL/workspace/vm3/schema.sh"

    # - name: Run Insert data script
    #   win_shell: |
    #     "bash /c/Users/DELL/workspace/vm3/insert_data"

    # - name: Run Delete data script
    #   win_shell: |
    #     "bash /c/Users/DELL/workspace/vm3/delete_data"

    # - name: Run Drop schema script
    #   win_shell: |
    #     "bash /c/Users/DELL/workspace/vm3/drop_schema"
    
    # - name: Stop vm 
    #   win_shell: |
    #     VBoxManage controlvm db-machine-3-oracle savestate
