- name: Start SQLLITE VM3
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to turn on VM-4 on remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/start-vm3.ps1
        dest: "C:\\Users\\DELL\\workspace\\vm3\\" 
      register: copy_result
    
    - name: Start VM-3 using Powershell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm3\start-vm3.ps1"

- name: Run sql files using sqlite
  hosts: vm-3
  become_user: amelia_user
  gather_facts: no
  tasks:

    - name: Download sqlite files
      copy:
        src: ~/bachelor/ansible-db/vm-3/sqlite-sakila-db
        dest: /home/amelia_user/
        owner: amelia_user
        group: amelia_user        
        mode: 0777

    - name: Run Insert schema script
      command: sqlite3 /home/amelia_user/database_sakila/sakila.db < /home/amelia_user/sqlite-sakila-db/sqlite-sakila-schema.sql
    
    - name: Run Insert data script
      command: sqlite3 /home/amelia_user/database_sakila/sakila.db < /home/amelia_user/sqlite-sakila-db/sql-server-sakila-insert-data.sql

    - name: Run Delete data script
      command: sqlite3 /home/amelia_user/database_sakila/sakila.db < /home/amelia_user/sqlite-sakila-db/sql-server-sakila-delete-data.sql

    - name: Run Drop schema script
      command: sqlite3 /home/amelia_user/database_sakila/sakila.db < /home/amelia_user/sqlite-sakila-db/sql-server-sakila-drop-objects.sql