- name: Start Oracle VM3
  hosts: windows
  gather_facts: no
  tasks:
    # - name: Delete powershell script to pull the newest changes
    #   win_file:
    #     path: "C:\\Users\\DELL\\workspace\\vm3\\"
    #     state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/start-vm3.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"  # Update the destination directory as per your workspace
      register: copy_result

    - name: Copy db scripts to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/sql-scripts/  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"  # Update the destination directory as per your workspace

    - name: Start vm script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm3\start-vm3.ps1"

    - name: Run Insert schema script
      win_shell: |
        "bash /c/Users/DELL/workspace/vm3/schema.sh"

    - name: Run Drop schema script
      win_shell: |
        "bash /c/Users/DELL/workspace/vm3/drop_schema"
    
    - name: Stop vm 
      win_shell: |
        VBoxManage controlvm db-machine-3-oracle savestate
