- name: Start Oracle VM3
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to turn on VM-3 on remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/start-vm3.ps1
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"  
      register: copy_result

    - name: Copy db scripts to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-3/sql-scripts/
        dest: "C:\\Users\\DELL\\workspace\\vm3\\"

    - name: Start VM-3 using Powershell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm3\start-vm3.ps1"
