- name: Start Oracle VM2
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm2\\start-vm2.ps1"
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-2/start-vm2.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm2\\"  # Update the destination directory as per your workspace
      register: copy_result

    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\start-vm2.ps1"
    
- name: Start postgress service
  hosts: vm-2
  gather_facts: no
  tasks:

    - name: Download postgres files
      copy:
        src: ~/bachelor/ansible-db/vm-2/postgres-sakila-db
        dest: /home/amelia_user/
        owner: amelia_user
        group: amelia_user        
        mode: 0777

    - name: Install PostgreSQL
      become: yes
      package:
        name: postgresql
        state: present

    - name: Ensure the PostgreSQL service is running
      become: yes
      service: 
        name: postgresql 
        state: started 
        enabled: yes

    - name: Execute SQL file
      become_user: amelia_user
      postgresql_db:
        name: amelia_user
        state: present
        login_user: amelia_user
        login_password: admin123
        login_host: localhost
        target: /home/amelia_user/postgres-sakila-db/postgres-sakila-schema.sql