- name: Start Oracle VM2
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm2\\start-vm2.ps1"
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-2/start-vm2.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm2\\"  # Update the destination directory as per your workspace
      register: copy_result

    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\start-vm2.ps1"
    
- name: Start postgress service
  hosts: vm-2
  gather_facts: no
  become: yes
  tasks:
    - name: Check if Postgres files exist
      stat:
        path: "~/bachelor/ansible-db/vm-2/postgres-sakila-db/"
      register: postgres_files_exist

    - name: Delete PowerShell script to pull the newest changes
      file:
        path: "~/bachelor/ansible-db/vm-2/postgres-sakila-db"
        state: absent
      when: postgres_files_exist.stat.exists

    - name: Download postgres files
      copy:
        src: ~/bachelor/ansible-db/vm-2/postgres-sakila-db
        dest: /root/ansible-db/postgres-sakila-db
        owner: root
        group: root        
        mode: 0777

    - name: Install PostgreSQL
      package:
        name: postgresql
        state: present

    - name: Ensure the PostgreSQL service is running
      service: 
        name: postgresql 
        state: started 
        enabled: yes