- name: Start Oracle VM2
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: "C:\\Users\\DELL\\workspace\\vm2\\start_vm2.ps1"
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-2/start_vm2.ps1  # Update the path to your PowerShell script
        dest: "C:\\Users\\DELL\\workspace\\vm2\\""  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Record the start time
      command: date +%s.%N
      register: start_time_vm

    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\start_vm2.ps1"

    - name: Record the end time
      command: date +%s.%N
      register: end_time_vm
    
    - name: Calculate the time difference
      set_fact:
        execution_time: "{{ (end_time_vm.stdout | float - start_time_vm.stdout | float) | round(3, 'floor') }}"

    - name: Display the execution time
      debug:
        msg: "Time taken to start VM with mysql installed: {{ execution_time }} seconds"
    
- name: Start postgress service
  hosts: vm-2
  gather_facts: no
  become: yes
  tasks:
    - name: Check if Postgres files exist
      stat:
        path: "~/bachelor/ansible-db/vm-2/postgres-sakila-db/"
      register: postgres_files_exist

    - name: Delete PowerShell script to pull the newest changes
      file:
        path: "~/bachelor/ansible-db/vm-2/postgres-sakila-db"
        state: absent
      when: postgres_files_exist.stat.exists

    - name: Download postgres files
      copy:
        src: ~/bachelor/ansible-db/vm-2/postgres-sakila-db
        dest: /root/ansible-db/postgres-sakila-db
        owner: root
        group: root        
        mode: 0777
    
    - name: Install dependencies for PostgreSQL
      apt: 
        name: "{{item}}" 
        update_cache: true 
        state: latest
      with_items:
      - bash
      - openssl
      - libssl-dev
      - libssl-doc

    - name: Install PostgreSQL 
      apt: 
        name: "{{item}}"
        update_cache: true 
        state: present
      with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
      become: yes

    - name: Ensure the PostgreSQL service is running
      service: 
        name: postgresql 
        state: started 
        enabled: yes

    - name: Ensure user is created
      become: true
      postgresql_user:
        name: amelia_user
        password: amelia_user
        priv: ALL
        state: present