- name: Start Oracle VM2
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-2/start-vm2.ps1 
        dest: "C:\\Users\\DELL\\workspace\\vm2\\"

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/vm-2/stop-vm2.ps1
        dest: "C:\\Users\\DELL\\workspace\\vm2\\"

    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\start-vm2.ps1"
    
- name: Start postgress service
  hosts: vm-2
  gather_facts: no
  tasks:

    - name: Download postgres files
      copy:
        src: ~/bachelor/ansible-db/vm-2/postgres-sakila-db
        dest: /home/amelia_user/
        owner: amelia_user
        group: amelia_user        
        mode: 0777

    - name: Install PostgreSQL
      become: yes
      package:
        name: postgresql
        state: present

    - name: Ensure the PostgreSQL service is running
      become: yes
      service: 
        name: postgresql 
        state: started 
        enabled: yes

    - name: Run Insert schema script
      become_user: amelia_user
      command: psql -U amelia_user -c '\i /home/amelia_user/postgres-sakila-db/postgres-sakila-schema.sql'
    
    - name: Run Insert data script
      become_user: amelia_user
      command: psql -U amelia_user -c '\i /home/amelia_user/postgres-sakila-db/postgres-sakila-insert-data.sql'

    - name: Run Delete data script
      become_user: amelia_user
      command: psql -U amelia_user -c '\i /home/amelia_user/postgres-sakila-db/postgres-sakila-delete-data.sql'

    - name: Run Drop schema script
      become_user: amelia_user
      command: psql -U amelia_user -c '\i /home/amelia_user/postgres-sakila-db/postgres-sakila-drop-objects.sql'

# - name: Stop Oracle VM2
#   hosts: windows
#   gather_facts: no
#   tasks:
#     - name: Run PowerShell script to stop VM
#       win_shell: |
#         powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\stop-vm2.ps1"