- name: Start Oracle VM2
  hosts: windows
  gather_facts: no
  tasks:
    - name: Delete powershell script to pull the newest changes
      win_file:
        path: C:\Users\DELL\workspace\vm2\start_vm2.ps1
        state: absent

    - name: Copy PowerShell script to remote host
      win_copy:
        src: ~/bachelor/ansible-db/start_vm2.ps1  # Update the path to your PowerShell script
        dest: C:\Users\DELL\workspace\vm2\  # Update the destination directory as per your workspace
      register: copy_result
    
    - name: Run PowerShell script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\Users\DELL\workspace\vm2\start_vm2.ps1"
